#!/usr/bin/env sh
YABAI="/Users/marlinortner/.config/yabai"
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m config debug_output on
# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
# move mouse to focused window
#yabai -m config mouse_follows_focus          on
yabai -m config window_placement             first_child 
#yabai -m config window_animation_easing      easeoutquint
#yabai -m config window_animation_duration    0.1
# floating windows always stay on top
#yabai -m config window_topmost               on
# enable borders
#yabai -m config window_border                on
# no clue what this is
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 off
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
BAR_HEIGHT=$(sketchybar --query bar | jq ".height")

BAR_HEIGHT=$(($BAR_HEIGHT + 5))

echo $BAR_HEIGHT
yabai -m config external_bar all:$BAR_HEIGHT:5
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   7

#Window Settings
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Systemeinstellungen$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Enpass$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
#yabai -m rule --add app="^Arc$" title="^$" mouse_follows_focus=off
#yabai -m rule --add app="^(Arc)$" subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
#yabai -m rule --add app="^Arc$" title="^Space.*$" manage=off layer=below
#yabai -m rule --add app="^Arc$" title="^$" manage=off layer=below
yabai -m rule --add app="^Arc$" title="^Space.*$" manage=off layer=below
yabai -m rule --add app="^Arc$" title="^$" manage=off layer=below
yabai -m rule --add app="^Maccy$" title="^$" manage=off layer=below
#Janky Borders
# set the correct starting active_color upon initializing yabai, based on number of windows in current space

# apps to start on specific spaces
yabai -m rule --add app="^Arc$" space=1
yabai -m rule --add app="^Obsidian$" space=2
yabai -m rule --add app="^iTerm2$" space=3
