#!/bin/bash
. ~/.config/sketchybar/colors.sh

export BAR_COLOR=0xFF101314
export BAR_COLOR_TRANS=0x00101314
export ITEM_BG_COLOR=0xffE1D94F
export ACCENT_COLOR=0xFFE1D950
# -- Teal Scheme --
options=(
	style=round
	width=6.0
	hidpi=on
    active_color=$ACCENT_COLOR
    inactive_color=$BAR_COLOR_TRANS
)

borders "${options[@]}"
	#active_color=0xffe2e2e3
	#inactive_color=0xff414550
    #inactive_color=$BAR_COLOR
